# Language codes shared by every slice that needs to offer a language picker — currently
# language_profiles (source/target languages) and media_library (manual subtitle
# search/upload). Lives at the top level, same pattern as config/ and backend_client/, so
# no slice has to reach into another slice's package for it.
SUPPORTED_LANGUAGES: list[tuple[str, str]] = [
    ("en", "English"),
    ("es", "Spanish"),
    ("es-419", "Spanish (Latin America)"),
    ("pt", "Portuguese"),
    ("pt-BR", "Portuguese (Brazil)"),
    ("fr", "French"),
    ("de", "German"),
    ("it", "Italian"),
    ("nl", "Dutch"),
    ("pl", "Polish"),
    ("sv", "Swedish"),
    ("no", "Norwegian"),
    ("da", "Danish"),
    ("fi", "Finnish"),
    ("tr", "Turkish"),
    ("ru", "Russian"),
    ("uk", "Ukrainian"),
    ("ar", "Arabic"),
    ("he", "Hebrew"),
    ("hi", "Hindi"),
    ("ja", "Japanese"),
    ("ko", "Korean"),
    ("zh", "Chinese (Simplified)"),
    ("zh-Hant", "Chinese (Traditional)"),
    ("th", "Thai"),
    ("vi", "Vietnamese"),
    ("id", "Indonesian"),
    ("ro", "Romanian"),
    ("cs", "Czech"),
    ("hu", "Hungarian"),
    ("el", "Greek"),
]
