"""add subtitle proxy registration

Revision ID: 6cb9853f56b6
Revises: 91ffead50677
Create Date: 2026-07-22 17:52:07.590321

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6cb9853f56b6"
down_revision: str | Sequence[str] | None = "91ffead50677"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "subtitleproxy",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("host", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_subtitleproxy_name"), "subtitleproxy", ["name"], unique=True)
    # SQLite can't ALTER a table to add a foreign key constraint directly — batch mode
    # (copy-and-move) is required, adjusted in from the autogenerated add_column/create_foreign_key.
    with op.batch_alter_table("subtitleproviderconfig") as batch_op:
        batch_op.add_column(sa.Column("proxy_id", sa.Integer(), nullable=True))
        batch_op.create_index(
            op.f("ix_subtitleproviderconfig_proxy_id"), ["proxy_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_subtitleproviderconfig_proxy_id_subtitleproxy",
            "subtitleproxy",
            ["proxy_id"],
            ["id"],
            ondelete="SET NULL",
        )


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table("subtitleproviderconfig") as batch_op:
        batch_op.drop_constraint(
            "fk_subtitleproviderconfig_proxy_id_subtitleproxy", type_="foreignkey"
        )
        batch_op.drop_index(op.f("ix_subtitleproviderconfig_proxy_id"))
        batch_op.drop_column("proxy_id")
    op.drop_index(op.f("ix_subtitleproxy_name"), table_name="subtitleproxy")
    op.drop_table("subtitleproxy")
