"""add genres to movie and series, last_aired to series

Revision ID: 0280fd8b7681
Revises: 85ca4be91828
Create Date: 2026-08-30 02:15:02.093733

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0280fd8b7681"
down_revision: str | Sequence[str] | None = "85ca4be91828"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("movie", sa.Column("genres", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column("series", sa.Column("genres", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column("series", sa.Column("last_aired", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("series", "last_aired")
    op.drop_column("series", "genres")
    op.drop_column("movie", "genres")
    # ### end Alembic commands ###
