"""baseline: language_profile

Revision ID: 086206ba585d
Revises:
Create Date: 2026-07-15 23:25:22.131771

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "086206ba585d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "languageprofile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_languages", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("target_languages", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("translation_provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("extract_embedded_subtitles", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_languageprofile_name"), "languageprofile", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_languageprofile_name"), table_name="languageprofile")
    op.drop_table("languageprofile")
    # ### end Alembic commands ###
