"""add acquired subtitle and subtitle blacklist entry tables

Revision ID: 0fbaa1a8ab67
Revises: 785ceab0c30c
Create Date: 2026-08-22 23:16:02.380468

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0fbaa1a8ab67"
down_revision: str | Sequence[str] | None = "785ceab0c30c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subtitleblacklistentry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("media_file_id", sa.Integer(), nullable=False),
        sa.Column("language", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("origin", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("release_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("download_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("blacklisted_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["media_file_id"], ["mediafile.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_subtitleblacklistentry_media_file_id"),
        "subtitleblacklistentry",
        ["media_file_id"],
        unique=False,
    )
    op.create_table(
        "acquiredsubtitle",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subtitle_id", sa.Integer(), nullable=False),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("release_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("download_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("acquired_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["subtitle_id"], ["subtitle.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_acquiredsubtitle_subtitle_id"), "acquiredsubtitle", ["subtitle_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_acquiredsubtitle_subtitle_id"), table_name="acquiredsubtitle")
    op.drop_table("acquiredsubtitle")
    op.drop_index(
        op.f("ix_subtitleblacklistentry_media_file_id"), table_name="subtitleblacklistentry"
    )
    op.drop_table("subtitleblacklistentry")
    # ### end Alembic commands ###
