"""add subtitle scan state and acquired subtitle upgrade check timestamp

Revision ID: 175cd2a539ac
Revises: 0280fd8b7681
Create Date: 2026-08-31 17:08:36.100845

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "175cd2a539ac"
down_revision: str | Sequence[str] | None = "0280fd8b7681"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subtitlescanstate",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("media_file_id", sa.Integer(), nullable=False),
        sa.Column("probed_at", sa.DateTime(), nullable=False),
        sa.Column("probed_size_bytes", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["media_file_id"], ["mediafile.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_subtitlescanstate_media_file_id"),
        "subtitlescanstate",
        ["media_file_id"],
        unique=True,
    )
    op.add_column(
        "acquiredsubtitle", sa.Column("last_upgrade_checked_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("acquiredsubtitle", "last_upgrade_checked_at")
    op.drop_index(op.f("ix_subtitlescanstate_media_file_id"), table_name="subtitlescanstate")
    op.drop_table("subtitlescanstate")
    # ### end Alembic commands ###
