"""add subtitle table

Revision ID: 1e5637d38860
Revises: 560423b7eaed
Create Date: 2026-07-27 22:31:22.954318

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1e5637d38860"
down_revision: str | Sequence[str] | None = "560423b7eaed"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subtitle",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("media_file_id", sa.Integer(), nullable=False),
        sa.Column("language", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("origin", sa.Enum("embedded", "external", name="subtitleorigin"), nullable=False),
        sa.Column("relative_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("track_index", sa.Integer(), nullable=True),
        sa.Column("scanned_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["media_file_id"], ["mediafile.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("media_file_id", "relative_path"),
    )
    op.create_index(op.f("ix_subtitle_media_file_id"), "subtitle", ["media_file_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_subtitle_media_file_id"), table_name="subtitle")
    op.drop_table("subtitle")
    # ### end Alembic commands ###
