"""add job_run table

Revision ID: 24c5a70efe05
Revises: 55bbdd9a9d00
Create Date: 2026-08-27 19:12:51.286260

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "24c5a70efe05"
down_revision: str | Sequence[str] | None = "55bbdd9a9d00"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobrun",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("queue", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=False),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_jobrun_finished_at"), "jobrun", ["finished_at"], unique=False)
    op.create_index(op.f("ix_jobrun_job_id"), "jobrun", ["job_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_jobrun_job_id"), table_name="jobrun")
    op.drop_index(op.f("ix_jobrun_finished_at"), table_name="jobrun")
    op.drop_table("jobrun")
    # ### end Alembic commands ###
