"""add download_even_if_target_embedded to language_profile

Revision ID: 26b381fb9308
Revises: 1087a8900a2e
Create Date: 2026-09-02 18:44:24.616051

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "26b381fb9308"
down_revision: str | Sequence[str] | None = "1087a8900a2e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default so the ADD COLUMN doesn't fail against existing rows on a NOT NULL
    # boolean column — adjusted in, autogenerate doesn't add it.
    op.add_column(
        "languageprofile",
        sa.Column(
            "download_even_if_target_embedded",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("languageprofile", "download_even_if_target_embedded")
    # ### end Alembic commands ###
