"""add poster_cached_at to media_metadata

Revision ID: 2a7fccdb8682
Revises: 24c5a70efe05
Create Date: 2026-08-27 20:46:16.941827

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2a7fccdb8682"
down_revision: str | Sequence[str] | None = "24c5a70efe05"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("mediametadata", sa.Column("poster_cached_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mediametadata", "poster_cached_at")
    # ### end Alembic commands ###
