"""add forced/HI/is_default to language_profile, language_profile_id to movie/series

Revision ID: 35527f37e677
Revises: 39f01288c6ac
Create Date: 2026-07-20 16:28:49.360416

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "35527f37e677"
down_revision: str | Sequence[str] | None = "39f01288c6ac"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default so the ADD COLUMN doesn't fail against existing rows on a NOT NULL
    # boolean column — adjust to fix the missing default autogenerate doesn't add.
    op.add_column(
        "languageprofile",
        sa.Column("forced", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "languageprofile",
        sa.Column("hearing_impaired", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "languageprofile",
        sa.Column("is_default", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # SQLite can't ALTER a table to add a foreign key constraint directly — batch mode
    # (copy-and-move) is required, adjusted in from the autogenerated create_foreign_key.
    with op.batch_alter_table("movie") as batch_op:
        batch_op.add_column(sa.Column("language_profile_id", sa.Integer(), nullable=True))
        batch_op.create_index(
            op.f("ix_movie_language_profile_id"), ["language_profile_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_movie_language_profile_id_languageprofile",
            "languageprofile",
            ["language_profile_id"],
            ["id"],
        )
    with op.batch_alter_table("series") as batch_op:
        batch_op.add_column(sa.Column("language_profile_id", sa.Integer(), nullable=True))
        batch_op.create_index(
            op.f("ix_series_language_profile_id"), ["language_profile_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_series_language_profile_id_languageprofile",
            "languageprofile",
            ["language_profile_id"],
            ["id"],
        )


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table("series") as batch_op:
        batch_op.drop_constraint(
            "fk_series_language_profile_id_languageprofile", type_="foreignkey"
        )
        batch_op.drop_index(op.f("ix_series_language_profile_id"))
        batch_op.drop_column("language_profile_id")
    with op.batch_alter_table("movie") as batch_op:
        batch_op.drop_constraint("fk_movie_language_profile_id_languageprofile", type_="foreignkey")
        batch_op.drop_index(op.f("ix_movie_language_profile_id"))
        batch_op.drop_column("language_profile_id")
    op.drop_column("languageprofile", "is_default")
    op.drop_column("languageprofile", "hearing_impaired")
    op.drop_column("languageprofile", "forced")
