"""add movie and series tables

Revision ID: 39f01288c6ac
Revises: e7c2e2ff2571
Create Date: 2026-07-20 14:19:40.338689

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "39f01288c6ac"
down_revision: str | Sequence[str] | None = "e7c2e2ff2571"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "movie",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("arr_service_id", sa.Integer(), nullable=False),
        sa.Column("arr_id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("remote_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["arr_service_id"],
            ["arrservice.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("arr_service_id", "arr_id"),
    )
    op.create_index(op.f("ix_movie_arr_service_id"), "movie", ["arr_service_id"], unique=False)
    op.create_table(
        "series",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("arr_service_id", sa.Integer(), nullable=False),
        sa.Column("arr_id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("remote_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["arr_service_id"],
            ["arrservice.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("arr_service_id", "arr_id"),
    )
    op.create_index(op.f("ix_series_arr_service_id"), "series", ["arr_service_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_series_arr_service_id"), table_name="series")
    op.drop_table("series")
    op.drop_index(op.f("ix_movie_arr_service_id"), table_name="movie")
    op.drop_table("movie")
    # ### end Alembic commands ###
