"""add translation_attempt table

Revision ID: 3e3a7c3f553b
Revises: 2a7fccdb8682
Create Date: 2026-08-28 10:15:07.769854

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3e3a7c3f553b"
down_revision: str | Sequence[str] | None = "2a7fccdb8682"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "translationattempt",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subtitle_id", sa.Integer(), nullable=False),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_language", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("target_language", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("translated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["subtitle_id"], ["subtitle.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_translationattempt_subtitle_id"),
        "translationattempt",
        ["subtitle_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_translationattempt_subtitle_id"), table_name="translationattempt")
    op.drop_table("translationattempt")
    # ### end Alembic commands ###
