"""add acquisition attempt audit trail table

Revision ID: 4cb2d5bc8e8b
Revises: 0fbaa1a8ab67
Create Date: 2026-08-23 23:42:59.934987

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4cb2d5bc8e8b"
down_revision: str | Sequence[str] | None = "0fbaa1a8ab67"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "acquisitionattempt",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subtitle_id", sa.Integer(), nullable=False),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("release_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("download_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("title_similarity", sa.Float(), nullable=False),
        sa.Column("resolution_matched", sa.Boolean(), nullable=True),
        sa.Column("source_matched", sa.Boolean(), nullable=True),
        sa.Column("codec_matched", sa.Boolean(), nullable=True),
        sa.Column("release_group_matched", sa.Boolean(), nullable=True),
        sa.Column("edition_matched", sa.Boolean(), nullable=True),
        sa.Column("replaced_attempt_id", sa.Integer(), nullable=True),
        sa.Column("attempted_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["replaced_attempt_id"], ["acquisitionattempt.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["subtitle_id"], ["subtitle.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_acquisitionattempt_subtitle_id"),
        "acquisitionattempt",
        ["subtitle_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_acquisitionattempt_subtitle_id"), table_name="acquisitionattempt")
    op.drop_table("acquisitionattempt")
    # ### end Alembic commands ###
