"""add prompt_template to translation_provider_config

Revision ID: 4d483fda231a
Revises: 552722b749d5
Create Date: 2026-08-16 12:56:37.031483

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4d483fda231a"
down_revision: str | Sequence[str] | None = "552722b749d5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "translationproviderconfig",
        sa.Column("prompt_template", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("translationproviderconfig", "prompt_template")
    # ### end Alembic commands ###
