"""add model column to translation provider config

Revision ID: 552722b749d5
Revises: facb42a665b3
Create Date: 2026-08-15 18:32:25.358987

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "552722b749d5"
down_revision: str | Sequence[str] | None = "facb42a665b3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "translationproviderconfig",
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("translationproviderconfig", "model")
    # ### end Alembic commands ###
