"""add size_bytes to subtitle

Revision ID: 55bbdd9a9d00
Revises: 61ab8904f7e2
Create Date: 2026-08-27 17:59:52.494509

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "55bbdd9a9d00"
down_revision: str | Sequence[str] | None = "61ab8904f7e2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default so the ADD COLUMN doesn't fail against existing rows on a NOT NULL
    # integer column — adjust to fix the missing default autogenerate doesn't add.
    op.add_column(
        "subtitle", sa.Column("size_bytes", sa.Integer(), nullable=False, server_default="0")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subtitle", "size_bytes")
    # ### end Alembic commands ###
