"""add mediafile table for filesystem scan results

Revision ID: 560423b7eaed
Revises: 751c5f997094
Create Date: 2026-07-26 12:29:10.105344

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "560423b7eaed"
down_revision: str | Sequence[str] | None = "751c5f997094"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mediafile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("movie_id", sa.Integer(), nullable=True),
        sa.Column("series_id", sa.Integer(), nullable=True),
        sa.Column("relative_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("scanned_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["movie_id"], ["movie.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["series_id"], ["series.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("movie_id", "relative_path"),
        sa.UniqueConstraint("series_id", "relative_path"),
    )
    op.create_index(op.f("ix_mediafile_movie_id"), "mediafile", ["movie_id"], unique=False)
    op.create_index(op.f("ix_mediafile_series_id"), "mediafile", ["series_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_mediafile_series_id"), table_name="mediafile")
    op.drop_index(op.f("ix_mediafile_movie_id"), table_name="mediafile")
    op.drop_table("mediafile")
    # ### end Alembic commands ###
