"""add media metadata

Revision ID: 577dfb7a48c8
Revises: 1e5637d38860
Create Date: 2026-08-01 13:09:04.577139

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from legendarr_backend.security.encrypted_string import EncryptedString

# revision identifiers, used by Alembic.
revision: str = "577dfb7a48c8"
down_revision: str | Sequence[str] | None = "1e5637d38860"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "metadataproviderconfig",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("api_key", EncryptedString(), nullable=True),
        sa.Column("connection_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_metadataproviderconfig_kind"), "metadataproviderconfig", ["kind"], unique=True
    )
    op.create_table(
        "mediametadata",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("movie_id", sa.Integer(), nullable=True),
        sa.Column("series_id", sa.Integer(), nullable=True),
        sa.Column("overview", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("poster_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("imdb_rating", sa.Float(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["movie_id"], ["movie.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["series_id"], ["series.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_mediametadata_movie_id"), "mediametadata", ["movie_id"], unique=True)
    op.create_index(op.f("ix_mediametadata_series_id"), "mediametadata", ["series_id"], unique=True)
    op.add_column("movie", sa.Column("tvdb_id", sa.Integer(), nullable=True))
    op.add_column("movie", sa.Column("imdb_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column("series", sa.Column("tvdb_id", sa.Integer(), nullable=True))
    op.add_column("series", sa.Column("imdb_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("series", "imdb_id")
    op.drop_column("series", "tvdb_id")
    op.drop_column("movie", "imdb_id")
    op.drop_column("movie", "tvdb_id")
    op.drop_index(op.f("ix_mediametadata_series_id"), table_name="mediametadata")
    op.drop_index(op.f("ix_mediametadata_movie_id"), table_name="mediametadata")
    op.drop_table("mediametadata")
    op.drop_index(op.f("ix_metadataproviderconfig_kind"), table_name="metadataproviderconfig")
    op.drop_table("metadataproviderconfig")
    # ### end Alembic commands ###
