"""add speech_to_text_fallback to language_profile

Revision ID: 5d46061b40b3
Revises: c75b7ff93c69
Create Date: 2026-08-25 21:25:49.661711

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5d46061b40b3"
down_revision: str | Sequence[str] | None = "c75b7ff93c69"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default so the ADD COLUMN doesn't fail against existing rows on a NOT NULL
    # boolean column — adjusted in, autogenerate doesn't add it.
    op.add_column(
        "languageprofile",
        sa.Column(
            "speech_to_text_fallback", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("languageprofile", "speech_to_text_fallback")
    # ### end Alembic commands ###
