"""add media_servers table

Revision ID: 61ab8904f7e2
Revises: c8ff5c2a3680
Create Date: 2026-08-26 12:18:55.504019

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from legendarr_backend.security.encrypted_string import EncryptedString

# revision identifiers, used by Alembic.
revision: str = "61ab8904f7e2"
down_revision: str | Sequence[str] | None = "c8ff5c2a3680"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mediaserverconfig",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("base_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("token", EncryptedString(), nullable=True),
        sa.Column("connection_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_mediaserverconfig_kind"), "mediaserverconfig", ["kind"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_mediaserverconfig_kind"), table_name="mediaserverconfig")
    op.drop_table("mediaserverconfig")
    # ### end Alembic commands ###
