"""drop translation_provider from language_profile

Revision ID: 6de10a94ec84
Revises: 35527f37e677
Create Date: 2026-07-20 17:39:55.646977

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6de10a94ec84"
down_revision: str | Sequence[str] | None = "35527f37e677"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_column("languageprofile", "translation_provider")


def downgrade() -> None:
    """Downgrade schema."""
    # server_default so the ADD COLUMN doesn't fail against existing rows on a NOT NULL
    # column — adjusted in from the autogenerated add_column, matching the model's old default.
    op.add_column(
        "languageprofile",
        sa.Column("translation_provider", sa.VARCHAR(), nullable=False, server_default="echo"),
    )
