"""add embedded track table

Revision ID: 85ca4be91828
Revises: 7544fd7bf786
Create Date: 2026-08-29 19:13:11.336710

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "85ca4be91828"
down_revision: str | Sequence[str] | None = "7544fd7bf786"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "embeddedtrack",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("media_file_id", sa.Integer(), nullable=False),
        sa.Column("track_index", sa.Integer(), nullable=False),
        sa.Column("codec_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("language", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("forced", sa.Boolean(), nullable=False),
        sa.Column("hearing_impaired", sa.Boolean(), nullable=False),
        sa.Column("extracted", sa.Boolean(), nullable=False),
        sa.Column("scanned_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["media_file_id"], ["mediafile.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("media_file_id", "track_index"),
    )
    op.create_index(
        op.f("ix_embeddedtrack_media_file_id"), "embeddedtrack", ["media_file_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_embeddedtrack_media_file_id"), table_name="embeddedtrack")
    op.drop_table("embeddedtrack")
    # ### end Alembic commands ###
