"""add translation_failure and acquisition_failure tables

Revision ID: a40d939e2129
Revises: 3e3a7c3f553b
Create Date: 2026-08-28 10:52:31.069036

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a40d939e2129"
down_revision: str | Sequence[str] | None = "3e3a7c3f553b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "acquisitionfailure",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("media_file_id", sa.Integer(), nullable=False),
        sa.Column("language", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("failed_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["media_file_id"], ["mediafile.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_acquisitionfailure_media_file_id"),
        "acquisitionfailure",
        ["media_file_id"],
        unique=False,
    )
    op.create_table(
        "translationfailure",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("media_file_id", sa.Integer(), nullable=False),
        sa.Column("source_language", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("target_language", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("failed_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["media_file_id"], ["mediafile.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_translationfailure_media_file_id"),
        "translationfailure",
        ["media_file_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_translationfailure_media_file_id"), table_name="translationfailure")
    op.drop_table("translationfailure")
    op.drop_index(op.f("ix_acquisitionfailure_media_file_id"), table_name="acquisitionfailure")
    op.drop_table("acquisitionfailure")
    # ### end Alembic commands ###
