"""add ocr_embedded_subtitles to language_profile

Revision ID: c75b7ff93c69
Revises: 4cb2d5bc8e8b
Create Date: 2026-08-24 18:26:39.182139

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c75b7ff93c69"
down_revision: str | Sequence[str] | None = "4cb2d5bc8e8b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default so the ADD COLUMN doesn't fail against existing rows on a NOT NULL
    # boolean column — adjusted in, autogenerate doesn't add it.
    op.add_column(
        "languageprofile",
        sa.Column(
            "ocr_embedded_subtitles", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("languageprofile", "ocr_embedded_subtitles")
    # ### end Alembic commands ###
