"""add path mapping prefixes to arr_service

Revision ID: e7c2e2ff2571
Revises: 4ccbcc02be10
Create Date: 2026-07-20 14:16:17.943967

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e7c2e2ff2571"
down_revision: str | Sequence[str] | None = "4ccbcc02be10"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "arrservice",
        sa.Column("remote_path_prefix", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "arrservice",
        sa.Column("local_path_prefix", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("arrservice", "local_path_prefix")
    op.drop_column("arrservice", "remote_path_prefix")
    # ### end Alembic commands ###
